apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlltVjViMjVrWlhkaGJHeGxkRHBpWlhsdmJsZGhiR3hsZERJd01Uaz0iCgkJfQoJfSwKCSJIdHRwSGVhZGVycyI6IHsKCQkiVXNlci1BZ2VudCI6ICJEb2NrZXItQ2xpZW50LzE5LjAzLjYgKGxpbnV4KSIKCX0KfQ==
type: kubernetes.io/dockerconfigjson
