# YAML for launching the orderer
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  serviceName: rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          # Image used
          image: rabbitmq:3-management
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: rabbitmq
              mountPath: /var/lib/rabbitmq
          ports:
            - containerPort: 15672
              name: manager
            - containerPort: 5672
              name: amqp
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: general
        resources:
          requests:
            storage: 1Gi

---
# Expose the port 7054 as ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-clusterip

spec:
  selector:
    app: rabbitmq

  ports:
    - name: rabbitmq-manager-clusterip
      port: 15672
    - name: rabbitmq-amqp-clusterip
      port: 5672
    # - name: rabbitmq-amqp-tls-clusterip
    #   port: 5671

  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-nodeport

spec:
  selector:
    app: rabbitmq

  ports:
    - name: rabbitmq-manager-nodeport
      port: 15672
      targetPort: 15672
      nodePort: 31672
    - name: rabbitmq-amqp-nodeport
      port: 5672
      targetPort: 5672
      nodePort: 30672

  type: NodePort
