apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: beyondewallet-ipfs
  labels:
    app: beyondewallet-ipfs
spec:
  serviceName: beyondewallet-ipfs
  replicas: 1
  selector:
    matchLabels:
      app: beyondewallet-ipfs
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: beyondewallet-ipfs
    spec: # pod spec
      containers:
        - name: beyondewallet-ipfs
          image: kmindz/go-ipfs
          # imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4001 # ipfs swarm
            #       - containerPort: 4002 # udp swarm
            - containerPort: 5001 # expose if needed/wanted
            - containerPort: 8080 # exposes if needed/wanted
          volumeMounts:
            - name: beyondewallet-ipfs-pvc
              mountPath: /var/ipfs
  volumeClaimTemplates:
    - metadata:
        name: beyondewallet-ipfs-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: do-block-storage
        resources:
          requests:
            storage: 1Gi

---
# Expose the port 30751 as node port -  NEEDED if you
# are interested in connecting to the Pods from the Host
# machine - keep in mind you would need the IP for the node
# port service
apiVersion: v1
kind: Service
metadata:
  name: beyondewallet-ipfs-clusterip

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: beyondewallet-ipfs

  ports:
    # - name: beyondewallet-ipfs-clusterip
    #   port: 4001
    - name: beyondewallet-ipfs-api-clusterip
      port: 5001
    - name: beyondewallet-ipfs-gateway-clusterip
      port: 8080

  type: ClusterIP

---
# Expose the port 30751 as node port -  NEEDED if you
# are interested in connecting to the Pods from the Host
# machine - keep in mind you would need the IP for the node
# port service
apiVersion: v1
kind: Service
metadata:
  name: beyondewallet-ipfs-nodeport

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: beyondewallet-ipfs

  ports:
    - name: beyondewallet-ipfs-api-nodeport
      port: 5001
      targetPort: 5001
      nodePort: 30501
    - name: beyondewallet-ipfs-gateway-nodeport
      port: 8080
      targetPort: 8080
      nodePort: 30880

  type: NodePort
