#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Balance transfer sample
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'ewallet'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['siliconvalley-orderer-clusterip:8443', 'siliconvalley-peer1-clusterip:9443', 'siliconvalley-peer2-clusterip:9443']
      #- targets: [‘peer0.siliconvalley.example.com:9443’, ‘peer1.siliconvalley.example.com:9444’, ‘peer0.org2.example.com:9445’, ‘peer1.org2.example.com:9446’, ‘orderer.example.com:8443’]
